planner:
  max_iterations: 2000
  step_size: 0.1
  goal_bias: 0.2
  rewire_radius: 0.5
  collision_check_resolution: 0.05
  smoothing_iterations: 150
  goal_threshold: 0.1
  early_exit: true
  ik_retries: 5
  ik_distinct_threshold: 0.2
  constraint_pos_tol: 0.005
  constraint_orn_tol: 0.05
  
  # Optionally override sampling limits for specific joints. 
  # Use 'null' to keep the default URDF limit.
  custom_limits:
    - null
    - [-3.14, 3.14] # Expand panda_joint2 sampling range
    - null
    - null
    - null
    - null
    - null


# Set weights for the distance metric. 
# If the list is shorter than the number of active joints, missing ones default to 1.0.
joint_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
